# -*- coding: utf-8 -*-
"""Simple Chatbot AI Agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WPtF9o_kMJUOgkmq8e0-kwwOaf2ZKiRi
"""

!pip install transformers torch

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Load pre-trained DialoGPT model and tokenizer
model_name = "microsoft/DialoGPT-medium"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

# Function to generate a response from the model
def generate_response(input_text, chat_history_ids=None):
    # Encode user input and add end-of-string token
    input_ids = tokenizer.encode(input_text + tokenizer.eos_token, return_tensors="pt")

    # Concatenate new input with chat history (if any)
    if chat_history_ids is not None:
        input_ids = torch.cat([chat_history_ids, input_ids], dim=-1)

    # Generate a response
    chat_history_ids = model.generate(
        input_ids,
        max_length=1000,
        pad_token_id=tokenizer.eos_token_id,
        no_repeat_ngram_size=3,
        do_sample=True,
        top_k=100,
        top_p=0.7,
        temperature=0.8
    )

    # Decode the generated response
    response = tokenizer.decode(chat_history_ids[:, input_ids.shape[-1]:][0], skip_special_tokens=True)

    return response, chat_history_ids

# Main chat loop
def chat():
    print("Chatbot: Hello! I'm your friendly AI chatbot. Type 'exit' to stop chatting.")
    chat_history_ids = None

    while True:
        user_input = input("You: ")

        if user_input.lower() == "exit":
            print("Chatbot: Goodbye!")
            break

        response, chat_history_ids = generate_response(user_input, chat_history_ids)
        print(f"Chatbot: {response}")

# Run the chatbot
if __name__ == "__main__":
    chat()